name: Run test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew  # Use this if gradlew is in the root directory

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Build APK
        run: ./gradlew assembleRelease  # Builds the release APK

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"  # Standard Android APK path
          tag: v.0.0.1
          token: ${{ secrets.TOKEN }}