name: Build and Release APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and restore Keystore file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > app/moncashPayment.jks

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Build APK
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Get version name
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Create and Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh release create "v${{ env.VERSION_NAME }}" \
            --title "Release v${{ env.VERSION_NAME }}" \
            --notes "Release v${{ env.VERSION_NAME }}" \
            "app/build/outputs/apk/release/app-release.apk#app-release.apk"