name : Run test

on :
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Run unit test
      run: ./gradlew clean testDebug

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run : flutter pub get
    - run : flutter build apk --release --split-per-abi

    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: v.0.0.1
        token: ${{ secrets.TOKEN}}